// generated by extract.py, im not doing allat
const KINKS = [
[
"Abasiophilia",
"A",
"An unusual type of kink involving attraction to people in neck braces, wheelchairs, casts, or other devices that impair mobility. It was first documented in a woman in the late 80s. It may be part of a medical fetish or enjoyed because it restricts movement."
],
[
"Abduction as seduction",
"A",
"A kink where the abductor/kidnapper treats the victim in a loving manner (can be related to gentle femdom)."
],
[
"Abrasions",
"A",
"People who enjoy this fetish like giving or receiving cuts and scrapes."
],
[
"Acarophilia",
"A",
"Arousal from scratching (tips for scratching during sex). Scratching is often an element incorporated into rough sex."
],
[
"Accidental stimulation",
"A",
"Refers to accidental physical stimulation and situations that arouse adrenaline and cause arousal."
],
[
"Acrotomophilia",
"A",
"Fetish for amputees. Fetishists may prefer a specific type of amputee (arm, leg, etc). A person with a fetish for being an amputee has apotemnophilia. There may be overlap with morphophilia, and some find these to be extreme fetishes."
],
[
"Actirasty",
"A",
"Arousal by the rays of the sun. This may be enjoyed through sex outside."
],
[
"Agalmatophilia",
"A",
"A person with this fetish is aroused by statues, mannequins, or other figurative representations. This may be related to Pygmalionism, an attraction to items of one’s own creation."
],
[
"Age play",
"A",
"Role play in which one or both partners pretend to be a different age/stage."
],
[
"Agoraphilia",
"A",
"A fetish dedicated to sex in public places. Here are the 48 best places to have sex if you have this fetish."
],
[
"Aliens",
"A",
"Kinksters fetishize having sex with aliens, often in an abduction and forced scenario."
],
[
"Altocalciphilia",
"A",
"A common kink for high heels, usually worn by women but not always."
],
[
"Amazons and authoritarians",
"A",
"Fetish dedicated to physically strong women like Amazons, women with strong/dominant personalities, or women in positions of authority. 19 tips to be sexually dominant in the bedroom."
],
[
"Amaurophilia",
"A",
"Kink for being unable to see, blinded, or blindfolded during sex."
],
[
"Anal penetration",
"A",
"A fetish for anal penetration with foreign objects (not sex toys or penises). Inserting objects that are not designed for anal safety (porous, without a flared base, with sharp edges) can cause damage."
],
[
"Anal sex",
"A",
"Both giving anal sex and receiving anal sex can be a kink or fetish. Penetrating a male with a strap on is also known as pegging (read our guide to pegging)."
],
[
"Anal toys worn under clothing",
"A",
"A fetish for using/wearing anal toys, such as using butt plugs during the day and not just during sex activity. It may be a command of a submissive by a dominant, part of anal training to take bigger items or penises, and/or as part of foreplay."
],
[
"Anal training",
"A",
"The practice of preparing one’s anus for inserting large items. How to train for anal."
],
[
"Anasteemaphilia",
"A",
"A fetish for people of extreme sizes, i.e., a giant or a dwarf. It can be used to refer to attraction to partners of differing heights, even if those people aren’t especially gigantic or tiny."
],
[
"Angelophilia",
"A",
"Fetish for angels"
],
[
"Anilingus",
"A",
"A kink for receiving or performing oral sex on the anus of someone, aka eating ass."
],
[
"Anonymous sex",
"A",
"A kink revolving around anonymous sexual encounters where one or both parties are unaware of the other’s identity. Gloryholes are a common form of anonymous sex, but they are not the only form."
],
[
"Aquaphilia",
"A",
"Fetish for water and having sex in water or around it. This can extend to a fetish for swimwear or posing in water, even if it doesn’t involve sexual activity."
],
[
"Autogynephilia",
"A",
"A kink where men present/dress as women (gynemimetophilia refers to men impersonating women). Autoandrophilia is arousal at the idea of being a man."
],
[
"Autofellatio",
"A",
"A kink where a man performs a blow job on himself. How to give a good blow job."
],
[
"Autoplushophilia",
"A",
"A type of plushophilia where a person is aroused by the idea of being a stuffed animal, especially a cartoonish one."
],
[
"Balloon fetish",
"B",
"AKA globophilia, involves being aroused by balloons, including their inflation, popping, appearance, or texture. Considered quite a weird fetish by some."
],
[
"Barebacking",
"B",
"Sex without a condom. Barebacking is especially common in the gay community, but this act can be dangerous and lead to STI transmission or pregnancy. Learn how and why you should use a condom."
],
[
"Bathroom control",
"B",
"When the dominant person controls when, how, and where the submissive can urinate or defecate. Extreme bathroom control can be dangerous."
],
[
"Begging",
"B",
"Freaky kink for begging and pleading (to have sex, for release/orgasm, to perform an act, etc.). Begging is submissive in nature. How to be a good submissive – 23 tips & behaviors."
],
[
"Belonephilia",
"B",
"Affinity to pins, needles, and sharp objects. Belonephilia can be quite dangerous. See also knife play."
],
[
"Bestiality",
"B",
"Sex with animals."
],
[
"Bimbofication",
"B",
"The process of making someone into a bimbo or being turned into a bimbo themselves. This might be a fun “punishment” for a bratty sub."
],
[
"Blindfolds",
"B",
"A type of bondage that blocks a person’s vision. See also amaurophilia."
],
[
"Body Inflation",
"B",
"The practice of inflating or pretending to inflate a part of one’s body, often for sexual gratification."
],
[
"Bondage",
"B",
"Restraint of a person, either by physical item (cuffs, rope, etc.) or instruction (known as mental bondage). Restraint can be full-body (vacuum beds, suspension) or involve a single body part, such as the eyes (blindfold), mouth (ball gag), wrists, or even thumbs. Bondage can be done alone, known as self-bondage, or may include furniture like sex swings and devices like handcuffs. Our bondage for beginners guide will help you get started."
],
[
"Body modification",
"B",
"Kink for a variety of body modifications. This may mean anything that changes the appearance of a body, from tattoos to piercings to saline injections, but this kink may also only refer to specific body mods, such as lip sewing."
],
[
"Branding",
"B",
"Marking someone with a symbol, word, etc. Typically uses a heated object (such as a metal hanger) to produce the brand. Branding is dangerous."
],
[
"Breath play",
"B",
"Choking and limiting breath. Being aroused by this is known as hypoxyphilia. This kink is a dangerous type of edge play."
],
[
"Breast/nipple torture",
"B",
"The breast equivalent of cock and ball torture. Torture may include hitting, pinching, bondage, and other methods of inflicting pain on the breasts."
],
[
"Breast/nipple worship",
"B",
"The act of worshipshipping someone’s breasts or nipples."
],
[
"Caning",
"C",
"The act of hitting someone with a rod known as caning. Fleshy areas such as the back of the thighs and butt are advised, but some people enjoy caning the bottoms of their partner’s feet."
],
[
"Capnolagnia",
"C",
"Fetish for smoking or watching others smoke"
],
[
"Castration",
"C",
"An extreme fetish involving the removal of all or part of a man’s genitals. Actual castration is incredibly dangerous. Most kinksters obsess over it without actually going through with it. This crazy kink goes hand in hand with emasculation fetishes as well as ball-busting, in which a man’s balls are crushed."
],
[
"CBT",
"C",
"Cock and ball torture (CBT) is pain applied to a man’s genitals. It may be a form of punishment. CBT can involve shoes, sounding, stretching, impact implements, and other tools. CBT can be dangerous."
],
[
"Chasmophilia",
"C",
"Aroused by crevices, caverns, or valleys."
],
[
"Chastity",
"C",
"A fetish where someone’s access to their genitals is blocked. Women wear chastity belts, and men wear cock cages that prevent erection and release. Also known as forced abstinence or forced celibacy. Chastity can be used as a form of self-denial or orgasm control, including ruined orgasms. How to give a ruined orgasm."
],
[
"Choking",
"C",
"Blood choking is the act of choking someone until they pass out. It is incredibly dangerous (which we wrote about before – check out our guide on choking during sex) and can lead to brain damage. Choking is a type of edge play."
],
[
"Claustrophilia",
"C",
"This fetish is the opposite of claustrophobia. A person becomes aroused or experiences orgasm through confinement to small spaces. This is a type of bondage."
],
[
"Clothed sex (endytophilia)",
"C",
"The affinity for sex while fully or partially clothed. You can enjoy this kink while lifting your skirt or dress, as your man penetrates you. Pushing underwear to the side can also be a form of this fetish."
],
[
"Cock and/or ball fetishization",
"C",
"An obsession with cock and balls."
],
[
"Cock worship",
"C",
"Similar to breast worship. This kind of kink involves verbal, physical, and mental adoration of a penis – including fake ones (strap-ons)."
],
[
"Collaring",
"C",
"For many types of submissives, the act of wearing a collar shows submission, loyalty, and/or devotion to a dominant. A collar may be seen as purely sexual or also romantic (similar to an engagement/wedding ring)."
],
[
"Consensual nonconsent",
"C",
"Situations where one or both parties have given prior consent for activities that may appear to be or actually involve nonconsent. Rape play is a common form. The “victim” has given prior consent to this type of play but seems to resist."
],
[
"Corsetry",
"C",
"The act of wearing a corset, sometimes to the extent of changing the shape and size of one’s body. Tight-lacing a corset enables successful waist training. Some dominants may use tight-lacing to limit breathing. It’s not just limited to your abs and tummy either."
],
[
"Coulrophilia",
"C",
"The kink for clowns, including jesters and/or mimes, won’t make many lists of common kinks."
],
[
"Cross-dressing",
"C",
"Dressing like a member of the opposite sex. For many people, it’s not necessarily sexual, while it is for others. Cross-dressing can involve clothing, accessories, makeup, and wigs."
],
[
"Crurophilia",
"C",
"A kink related to legs."
],
[
"Crush fetish",
"C",
"A particular fetish relating to crushing small animals or objects. Squashing kink is a similar obsession."
],
[
"Cunnilingus",
"C",
"This kink can be geared towards receiving oral sex as a woman or giving it either as a man or woman. Cunnilingus plays well with pussy worship. If your partner has a kink for licking pussy, you won’t need to convince him to go down on."
],
[
"Cupping",
"C",
"Small cups or jars are applied upside down to the body, usually the back. Fire or a hand-pump creates suction that results in temporary bruising and a tight feeling. Extreme cupping can break the skin, but cupping is considered safe (the flame is only used for suction and doesn’t burn the skin)."
],
[
"Dacryphilia",
"D",
"Arousal caused by tears or crying."
],
[
"Degradation",
"D",
"If you like it when your man talks down to you during sex, you might be into degradation. This is one of those kinks that works especially well with domination and submission. Just because you like doing it (giving or receiving) during sex doesn’t mean you think any less of your partner. However, not everyone likes degradation, and that’s okay."
],
[
"Dendrophilia",
"D",
"Also known as Arbophilia, and one of the most interesting kinks people have. A sexual attraction to trees, either because they are phallic-shaped or because of the texture. May overlap with xylophilia."
],
[
"Diapers",
"D",
"This fetish is usually part of infantilism – but not always."
],
[
"Discipline",
"D",
"Giving or receiving punishment for perceived or defined infractions. Discipline is a major part of many power exchange relationships and something typically desired by masochists and administered by sadists. 16 punishment ideas for subs."
],
[
"Dirty talking",
"D",
"Having a kink for talking dirty during sex is pretty tame. Some people might not even consider it a fetish! See also narratophilia. How to talk dirty + 73 dirty talk phrases."
],
[
"Doraphilia",
"D",
"Playing with skin, leather, or fur. Hyphephilia is a similar fetish for touching hair, fur, skin, and certain fabrics."
],
[
"Double penetration",
"D",
"Penetration of a woman’s vagina and ass via a combination of toys, penises, or both. Double penetration may be part of a group sex scenario (MFM), which often occurs in the swinging lifestyle."
],
[
"Dracophilia",
"D",
"A fetish for dragons. Fantasy fetish companies such as Bad Dragon make dragon dildos, including those that ejaculate!"
],
[
"DVP",
"D",
"Stands for double vaginal penetration. Unlike double penetration (DP), which is simultaneous anal and vaginal penetration, DVP involves two penises or one penis and one toy in the vagina. It can be satisfying for all parties, although it requires lube and preparation. In DVP, only one partner may have enough room to thrust."
],
[
"Edge play",
"E",
"Any risky or extreme kink or fetish. Examples include choking, breath play, knife play, fire play, and any activity that results in bleeding."
],
[
"Elastophilia",
"E",
"A fetish for stretchy materials, including spandex, latex, silicone, etc. Elastophiles often enjoy bouncing on these materials or sinking deep down into something stretchy."
],
[
"Electric play",
"E",
"Playing with uncontrolled electricity is very dangerous and can even lead to heart failure. However, most people (aside from those with pacemakers, heart issues, and other implants), can safely play with TENS units or violet wands to explore this kink."
],
[
"Endytophilia",
"E",
"Arousal by having sex with a partner who is wearing clothes during the act."
],
[
"Enemas (klismaphilia)",
"E",
"Inserting a tube into the anus and using a liquid (typically water, but other solutions may be utilized, including urine) to clean out the rectum. Enemas may be used to prepare for anal activities, but this is not necessary. An enema could be a form of punishment or control."
],
[
"Enkuopoiphilia",
"E",
"Impregnation fetish or breeding. We have an entire guide on the breeding kink."
],
[
"Eproctophilia",
"E",
"Arousal from flatulence (farts). It’s a type of olfactophilia."
],
[
"Exhibitionism",
"E",
"A common fetish for being naked and performing sexually in front of a person or persons. Masturbating for your partner is a mild form of this kink, but performing in sex windows or at BDSM shows and parties is a safe way to explore this fetish. Sex in public is partly exhibitionism. Related to agrexophilia, which is arousal when other people know about your sexual activities, and autagonistophilia, exposing oneself while on stage and being photographed. The counterpart of voyeurism."
],
[
"Exoticism",
"E",
"Fetishizing members and elements of Far Eastern culture (Japan, China, etc.), including fictional worlds inspired by these locations. A preoccupation with Geishas is common in the Western world, for example, with this fetish. See also Otherness."
],
[
"Face fucking",
"F",
"An extreme form of blow job where a man roughly fucks a partner’s mouth. This kink isn’t inherently dangerous, but it can be uncomfortable and lead to tears, gagging, and even vomiting."
],
[
"Face sitting",
"F",
"The act of a woman sitting on a man’s face while he performs oral sex. Face sitting can include mild suffocation, but doesn’t have to. It’s incredibly dominant. Check out other ways to dominate your man."
],
[
"Face slapping",
"F",
"A slap across the face brings you to attention and corrects your mistakes. You’re unlikely to enjoy this fetish unless you’re a bit of a masochist, but it’s not as far out as some items on our list of every kink. Slapping during sex guide."
],
[
"Fat fetishism",
"F",
"The sexual attraction to overweight or obese people due to their weight and size. Gaining or feederism (mentioned below as “Forced feeding”) is a variation of fat fetishism where the sexual attraction/gratification is not solely gained from the “fatness” but more from the process of gaining weight/getting fat. Check out the 12 best sex positions for fat people."
],
[
"Fellatio",
"F",
"Not usually deemed a fetish or kink, but it can be for some. Check out the Blow Job Guide for tips."
],
[
"Fictophilia",
"F",
"A sexual attraction toward fictional characters, usually an unrequited pining"
],
[
"Figging",
"F",
"Using ginger root to create a burning sensation. It must be peeled before it can be inserted anally or vaginally."
],
[
"Fighting/Wrestling",
"F",
"Play fighting and wrestling is sexy because of your body proximity as you struggle to maintain control. Even if you lose, you don’t really lose! If you’re turned on by a fight between other people, you’re not alone, either."
],
[
"Fire play",
"F",
"A form of edge play that involves flames and fire. Talk about a hardcore kink! Fire play can be dangerous and disgusting because hair can burn off and smell terrible (consider shaving first). Fire/heat may be contrasted with another type of kink: cold/ice."
],
[
"Fisting",
"F",
"The act of penetration with a full hand is certainly an interesting kink. Unlike the name suggests, your partner should start with your hand straight and thumb tucked under his fingers like a duck bill. After he inserts his knuckles – the widest part of his hand – he can curl his fingers into a fist/ball shape. Fisting requires time, patience, trust, and lots of lube."
],
[
"Flogging (flagellation)",
"F",
"Hitting someone with a multi-tailed tool known as a flogger. Depending upon the strength of the swing, flogging can range from a warm-up to a harsh impact that draws blood. Flogger tails come in many materials: fur, leather, suede, rubber, silicone, and ball-chain, to name a few."
],
[
"Food play",
"F",
"Incorporating food into sex is often on kink lists. This may mean using someone as a dish or table, covering your partner’s body with food and licking it off (think whipped cream or chocolate sauce, but you can get creative!). Food play can be a fun kink, but beware that playing with food near your vagina could contribute to a yeast infection. A fetish for food is known as sitophilia."
],
[
"Foot fetish (podophilia)",
"F",
"A foot fetishist enjoys feet sexually. This may involve footjobs, licking, sucking, and massaging. Foot worship in a power exchange scene can take the form of polishing shoes or boots, even with a tongue or worshipping feet! Some consider it a nasty kink, while others love it."
],
[
"Forced feeding",
"F",
"A wild kink for forcing someone to eat, potentially until they gain weight. This fetish is a type of body modification fetish. Feederism sometimes refers specifically to men feeding women, but it can also be used without distinction."
],
[
"Formicophilia",
"F",
"Arousal by insects or by insects crawling on and nibbling the body. Not a basic kink at all! The fetish for bees and wasps specifically is known as melissophilia, while an attraction to spiders is known as arachnophilia."
],
[
"Forniphilia",
"F",
"A BDSM kink involving people acting as human furniture that others use."
],
[
"Frotting",
"F",
"Rubbing of two penises together. One man may hold the penises together during this act. Similar activities include frottage (rubbing while clothed for sexual stimulation) and frotteurism (rubbing or fondling an unsuspecting/non-consenting person). All are hot kinks!"
],
[
"Furries",
"F",
"This kink is hot, literally. Furries dress as animals or humanoid animal creatures, sometimes decked head-to-toe in fur. They often don animalistic dildos via strap-ons to enhance their furry play. Many furries engage in role playing games and cosplay as part of their lifestyle, which can become quite expensive."
],
[
"Gags",
"G",
"A form of mouth bondage. Gags come in many forms, but ball gags are the most common. They may also take the form of a bit, cleave, pacifier, penis, or spider gag, among others. Mouth gags aren’t usually dangerous, but they can be uncomfortable. Make sure to fit the gag properly to your (or your partner’s) mouth."
],
[
"Gerontophilia",
"G",
"Attraction to someone from a much older age group. May-December relationships can fall into this kink if the members of the couple specifically fetishize the age difference."
],
[
"Golden showers",
"G",
"See watersports."
],
[
"Group sex (Polyiterophilia)",
"G",
"Group sex and multiple-party scenarios can be quite hot, but they can also be uncomfortable. Threesomes are one of the more common arrangements (and a fascination with three-person sex is known as troilism). Learn how to have a threesome and use these satisfying threesome positions."
],
[
"Haematomania, aka hematolagnia",
"H",
"Lust for blood and bleeding. May include wounds, vampirism or biting to draw blood. It goes without saying that this kink is obviously quite dangerous."
],
[
"Harpaxophilia",
"H",
"The fetish for being robbed. Can be played as a role in consensual non-consent. Chrematistophilia is a similar kink to being forced to pay for sex."
],
[
"Helplessness",
"H",
"Any role in which someone is helpless. They may be the victim to their role play partner (robber, kidnapper, etc), or their partner may act as a savior (think of a princess who needs saving or an inept housewife)."
],
[
"Homeovestism",
"H",
"Attraction to the clothing of one’s own gender or by people wearing the clothing accepted as appropriate for their gender by society. This fetish was first defined by George Zavitzianos."
],
[
"Hybristophilia",
"H",
"Arousal by the knowledge that one’s partner has committed a heinous act or crime. This weird kink includes cheating, lying, robbery, or murder. This is sometimes known as Bonnie and Clyde Syndrome after the American bank-robbing and murdering duo. One partner is turned on by the other’s bad deeds. Some people find themselves attracted to criminals who are in prison."
],
[
"Hypnotism",
"H",
"In an erotic situation, hypnosis could be a form of consensual nonconsent. Try out this kink with some sexy magician/assistant role play."
],
[
"Hypoxia",
"H",
"Paraphilia for being submerged under water to restrict breathing, a type of erotic asphyxiation. This kink can be fatal."
],
[
"Immobility",
"I",
"A sex kink involving bondage that may also include forced feeding."
],
[
"Impact play",
"I",
"Any activity involving hitting, either with body parts or other tools. Hitting, punching, spanking, flogging, whipping, and paddling are just a few forms of impact play, and intensity varies with the tool and effort."
],
[
"Impregnation",
"I",
"The fascination with making someone pregnant/conception during sex, typically from a man’s point of view."
],
[
"Imprisonment",
"I",
"Obsession with being locked inside cages, cells, coffins, or other areas."
],
[
"Infantilism",
"I",
"A specific type of age play where someone plays an infant/baby. This can involve pacifiers, diapers, bottles, etc. A second person may act as a nanny or parent."
],
[
"Internal cumshots",
"I",
"Similar to a semen fetish, but arousal is due to being ejaculated into rather than on. If you’re trying to avoid pregnancy, anal sex is the only safe way to engage in this kink. But STIs can be transmitted through semen even during anal sex. Also known as a creampie fetish"
],
[
"Intercrural or interfemoral sex",
"I",
"Thrusting between someone’s thighs without penetration. How to thrust during sex."
],
[
"Intoxication",
"I",
"Taking drugs or alcohol during or before a sex scene. Intoxication can lead to poor decision-making, risky behavior, and mistakes that could be dangerous or even fatal, especially when mixed with edge play."
],
[
"Japanese bondage (Shibari)",
"J",
"Some people have a kink for these intricate ties,"
],
[
"Jerk off instructions (JOI)",
"J",
"Being instructed to masturbate."
],
[
"Katoptronophilia",
"K",
"A fetish for having sex in front of mirrors, a fairly common sexual kink."
],
[
"Keraunophilia",
"K",
"A sexual fascination with thunder and lightning – similar to arousal from thunderstorms (brontophilia). You can’t incorporate it into your sex, but a thunderstorm makes a good backdrop for sexy times! Many people find that their desire levels increase during storms."
],
[
"Kigurumi",
"K",
"A fetish all about wearing anime masks, specifically men who wear masks of women."
],
[
"Knife play",
"K",
"A type of edge play activity that involves actual knives or blades or the implication of them. Breaking someone’s skin during kinky sex could be quite dangerous."
],
[
"Lactation",
"L",
"A lactation fetishist is all about lactating mammaries, that is, boobs producing milk. Many women enjoy the sensation of nipple suckling, and their partners enjoy breastfeeding. Lactation fetishists may encourage lactation when it wouldn’t naturally occur because the milk specifically is their kink (lactophilia), or engage in breastfeeding without milk. How to breastfeed your man."
],
[
"Latex/rubber",
"L",
"Latex, rubber, PVC, and similar materials catch the eye with their sheen. They make for perfect fetish photography, too. Fortunately, you can get your kink on with the help of many retailers that specialize in latex gear and clothing."
],
[
"Lesbophilia",
"L",
"Men with a lesbian kink enjoy lesbian sex more than your typical male. Some may go so far as to imagine themselves as women in girl-on-girl scenarios. These 14 lesbian sex positions will give you some inspiration."
],
[
"Lingerie",
"L",
"Some people have kinks for lingerie, including buying and wearing it, even if it’s designed for the opposite gender"
],
[
"Lithophilia",
"L",
"A kink for rocks, stones, or gravel. This can be used nonsexually."
],
[
"Macro Fetish",
"M",
"People with this kink enjoy partners who are giant. This may mean plus-sized, but it can mean giants in the realm of fantasy role playing and writing."
],
[
"Macrogenitalism",
"M",
"A fetish for genitals that are particularly large. This isn’t limited just to penises."
],
[
"Maiesiophilia",
"M",
"Sexual attraction to pregnant women or giving birth."
],
[
"Maschalagnia",
"M",
"A fetish dedicated to armpits, including kissing, licking, and smelling. This kink may also involve inserting penises in the armpit for stimulation."
],
[
"Masochism",
"M",
"Enjoyment of pain, punishment, and torture. Someone who feels this is known as a masochist. Masochists are often, but not always, submissive and may also have a pleasure kink to balance things out."
],
[
"Mechanophilia",
"M",
"Sexual attraction to and arousal by machines makes this kinky list. While other fetishes objectify robots, this one can include a wider variety and may also go along with the desire to have sex in or on a machine, such as a car, bike, plane, etc."
],
[
"Medical play",
"M",
"Role play involving medical scenarios, medical implements (scalpels, needles, speculums, etc), and/or medical uniforms. Medical play often involves an examination of one person by the “doctor,” who may take advantage of the situation. Play piercing is also common in medical play. Any play that breaks the skin can be dangerous if an infection occurs."
],
[
"Menophilia",
"M",
"An obsession with menstrual blood. Fetishists of this type don’t mind period sex. In fact, they may prefer it. And they might like going down on a woman when she has her period."
],
[
"Merinthophilia",
"M",
"The fetish for bondage. See also vincilagnia from our list of sex kinks."
],
[
"Mess fetish (hygrophilia)",
"M",
"If you would rather avoid the wet spot on the bed, then this dirty kink probably isn’t for you. Mess fetishists enjoy the mess created by sexual fluids, both male and female fluids. They may use the fluids as lube, to drink, to “paint” on their partner’s body, or pass it back and forth orally (snowballing)."
],
[
"Micro fetish",
"M",
"The opposite of a macro fetish. Kinksters enjoy when partners are much smaller than them or being the smaller partner. Those who fall into the latter group may enjoy the feeling of being crushed during sex."
],
[
"Military",
"M",
"A military fetish that often goes hand in hand with a uniform fetish."
],
[
"Mixophilia",
"M",
"A kink related to watching yourself having sex. Recording sex and mirrors are two ways to enjoy this kink."
],
[
"Morphophilia",
"M",
"People with this fetish are attracted to bodies and body parts that are different from the norm. They might enjoy amputees, dwarves, or people with other deformities."
],
[
"Mummification",
"M",
"A kink where someone is bound entirely or nearly entirely to prevent almost all movement. A vacuum bed can achieve full mummification, as can plastic wrap, but it can be dangerous if bindings prevent airflow. Mummification can also involve extreme temperatures, so hydration is essential for doing it safely."
],
[
"Muscles",
"M",
"Some people have a fetish for defined or large muscles. Muscle worship is one variant of this kink."
],
[
"Mysophilia",
"M",
"This fetish is for dirt and items that have been dirtied, especially by bodily fluids during sex. Used underwear is a common example."
],
[
"Narratophilia",
"N",
"A fetish shared by those who enjoy telling and listening to dirty stories, talking about sex or incorporating dirty talk into sex."
],
[
"Nasolingus",
"N",
"A fetish for sucking on someone’s nose."
],
[
"Nasophilia",
"N",
"Fetish for noses."
],
[
"Necrophilia",
"N",
"The fetish for human corpses."
],
[
"Necrozoophilia",
"N",
"Fetish for deceased animals."
],
[
"Needle play",
"N",
"Playing with needles can involve breaking the skin and temporary piercing. Needles can also be used to scratch."
],
[
"Nonconsensual",
"N",
"A kink for sex without consent (rape). All nonconsensual sexual activities and play are forms of sexual assault or rape. This is illegal, traumatizing, and can be dangerous."
],
[
"Nullification",
"N",
"A kink for removing any body part. This is very dangerous."
],
[
"Nullo",
"N",
"An extreme kink for the removal of genitals. In practice, nullo is very dangerous and can even be fatal."
],
[
"Nyctophilia",
"N",
"Fetish for the night that can also refer to fetishizing darkness. Scotophilia has the same meaning."
],
[
"Objectophilia (Objectum Sexuality)",
"O",
"Also known as fetishism. This refers specifically to arousal by and sexual activity with an inanimate object, such as shoes."
],
[
"Oculolinctus",
"O",
"Desire to lick eyeballs."
],
[
"Oculophilia",
"O",
"An obsession with the eyes."
],
[
"Odontophilia",
"O",
"The general fetish for teeth, which can include biting, licking teeth, or even removing them."
],
[
"Olfactophilia",
"O",
"Attraction to smells, especially pungent body odors. Osmolagnia is the fetish for sweat or gaseous emissions specifically."
],
[
"Omorashi",
"O",
"The Japanese word for a fetish related to having a full bladder and urinating on oneself. Often shortened to “omo.”"
],
[
"Orgasm denial",
"O",
"A type of play where someone’s orgasm is denied entirely, limited/ruined, or delayed."
],
[
"Otherness",
"O",
"Sexual attraction to someone from other places, including aliens. See xenophilia and exoticism."
],
[
"Pantyhose fetish",
"P",
"Arousal from pantyhose, usually seeing someone put them on and/or wear them, and sometimes involves ripping, but the item can be arousing when not worn. Some prefer specific styles such as visible seams."
],
[
"Parthenophilia",
"P",
"A fetish for virginal partners."
],
[
"Partialism",
"P",
"Sexual obsession with specific body parts and not the whole. Eyes, faces, forearms, and feet are all common objects of obsession, but any body part will do."
],
[
"Pecattiphilia",
"P",
"Fetish for sinning and breaking religious rules."
],
[
"Pediophilia",
"P",
"Fetish for dolls, especially sex dolls."
],
[
"Penis Humiliation",
"P",
"A kink involving insulting a man’s penis, including size, appearance, and performance. There are many ways people get off on humiliation, insulting, and degradation."
],
[
"Peodeiktophilia",
"P",
"Showing one’s penis to others (flashing)."
],
[
"Pet play",
"P",
"Any kink where someone acts like a domesticated pet. Cats and dogs are especially common with leashes, collars, and food/water dishes used as props."
],
[
"Phalloorchoalgolagnia",
"P",
"Arousal from pain directed toward male genitals. See also cock and ball torture (CBT)."
],
[
"Phallophilia",
"P",
"Obsession with large penises."
],
[
"Phobophilia",
"P",
"Sexual obsession with being afraid. This fetish can be directed toward hate as well as fear."
],
[
"Phygephilia",
"P",
"Fetish for being a fugitive on the run."
],
[
"Pictophilia",
"P",
"Fetish for watching pornography, especially of the same actor."
],
[
"Play piercing (Piquerism, Picquerism)",
"P",
"A play piercing is performed for temporary decoration as well as for the sensation of breaking the skin."
],
[
"Plushophilia",
"P",
"A fetish or paraphilia for stuffed animals. These people may have a kink specifically for teddy bears, and they may be furries. Reddit has numerous communities on stuffed animals."
],
[
"Pony play",
"P",
"A kink for acting like a pony or its master. “Ponies” can wear everything from blinders to bits to bridles to fake ears and hooves. Ponies are trained by their masters and may even do manual labor."
],
[
"Psychrophilia",
"P",
"Arousal by being cold or watching others be cold. Having sex in freezers, meat lockers, or around ice might fulfill this kink. In other contexts, a psychrophile is an organism, such as a bacterium, that grows at extreme temperatures, like at the poles or in the deep ocean."
],
[
"Pregnancy",
"P",
"This kink goes beyond a woman’s pregnant glow. Some people just can’t get enough of a pregnant woman’s powerful and sexy body. It’s so common that there are multiple names for it, including preggophilia and maieusophoria. Your partner may even be surprised by how turned on he is when you’re pregnant – and your hormones might have you wanting more sex, too."
],
[
"Psychrocism",
"P",
"Fetish dedicated to being cold, having sex with a cold partner, or using cold objects (ice cubes, cold dildos, etc) during sex."
],
[
"Pteronphilia",
"P",
"Kink for being tickled specifically by feathers."
],
[
"Pubephilia",
"P",
"Obsession with pubic hair. A love for pubic hair has been expressed in literature and art."
],
[
"Pygmalionism",
"P",
"Sexual obsession with human-like images, especially when you made it yourself. This fetish may lead to stimulating oneself with statues or mannequins."
],
[
"Pygophilia",
"P",
"Partialism to butts and seeing, touching, and playing with them."
],
[
"Pyrolagnia",
"P",
"Sexual arousal from watching or setting fires. Playing with fire is dangerous. At least one study has been done on the subject."
],
[
"Pyrophilia",
"P",
"A fascination with fire. Setting fires and using fire during sex can be dangerous. However, massage candles can be used safely because of the wax’s low melting point, and fire cupping is generally safe."
],
[
"Quirofilia",
"Q",
"Fetish for hands. Some people fetishize certain parts of the hand, such as the fingers or fingernails. Others may prefer hands of a certain size or shape. Still others with this fetish may enjoy seeing hands performing certain actions. It could be masturbation or something nonsexual, such as washing the dishes."
],
[
"Quiet sex",
"Q",
"Intense arousability for sex that’s quiet or silent, perhaps because someone can overhear. Can incorporate gags."
],
[
"Rape fantasy",
"R",
"A fetish for acting out a pretend rape (consensual nonconsent). This fantasy can occur on both the victim’s and the perpetrator’s sides. Arousal at the idea of rape is known as raptophilia. Discover other common sexual fantasies."
],
[
"Revving",
"R",
"Kink for watching someone rev an engine, especially when they wear heels. Also known as “pedal pushing” or “pedal pumping.” There are plenty of explicit and non-explicit videos online, featuring women in bare feet or high heels pushing the gas pedal. Sometimes these women are referred to as gas pedal honeys."
],
[
"Retifism",
"R",
"The fetish for shoes and footwear. Also known as altocalciphilia."
],
[
"Rhabdophilia",
"R",
"A fetish for receiving physical beatings such as flogging or whipping."
],
[
"Robotism",
"R",
"A freaky kink for androids (male robots), gynoids (female robots), or cyborgs."
],
[
"Ropework",
"R",
"A kink for rope used for bondage. Popular types of ropework include the Japanese-inspired shibari, more correctly called “Kinbaku”. Why not put that on your sex list?!"
],
[
"Rimming",
"R",
"A kink for giving or receiving rim jobs."
],
[
"Sadism",
"S",
"The kink for providing pain; can be related to a dom kink. Masochists and sadists often come together to meet one another’s kinky needs."
],
[
"Savantophilia",
"S",
"A fetish for people who have a cognitive impairment or delay."
],
[
"Scar fetish",
"S",
"Sexual attraction to scars from surgeries, injuries, often because they represent risk-taking or masculinity. Romance books have plenty of kink examples for this one."
],
[
"Scatophilia",
"S",
"A fetish for fecal matter. Also known as coprophilia. One of the most taboo kinks."
],
[
"Sensation play",
"S",
"A light sex kink where partners exchange sensations on the skin. Items with different textures (soft, hard, bumpy, smooth, cold, hot, etc) can be run across the skin. Pain isn’t involved, but you can alternate between pain and sensation during light BDSM play."
],
[
"Sensory deprivation",
"S",
"Any play that prevents someone from using one of their five senses. Blindfolds block sight, gloves prevent touch, earmuffs deprive the sense of hearing, etc. How to explore your sensory deprivation kink."
],
[
"Siderodromophilia",
"S",
"A fetish for trains or engaging in sexual activity on a train."
],
[
"Slime fetish",
"S",
"A type of kink for slime and slimy things. Tentacles are a prime example of a slime fetish in popular media. This fetish is closely related to the mess fetish."
],
[
"Sneezing Fetish",
"S",
"A kink for watching someone else sneeze. This person is usually naked. Sneezing elicits a bodily response somewhat similar to orgasm. People with a sneeze fetish might also participate in tickling and forced urinating kinks."
],
[
"Snuff",
"S",
"A fantasy fetish for killing someone or being killed. Snuff is often considered to be an urban legend. It’s obviously dangerous and illegal in practice."
],
[
"Somnophilia",
"S",
"The fetish for sexual partners who are asleep. It is a rare fetish. People with this fascination may enjoy the “sleeping princess” trope. In reality, a partner should specify prior consent to sexual activity that happens or begins while they are asleep because sleeping people cannot give consent. Definitions differ, however."
],
[
"Sounding",
"S",
"A kink for inserting thin tubes, usually made of glass or metal, into the urethra. This is one of the most common kinks involving urethral play. Kinksters often use medical sounds or similar tools, and sounding can be part of medical play. Sounding can be dangerous, especially if the inserted item breaks off inside or isn’t sanitized beforehand, but that doesn’t stop it from being one of the top fetishes."
],
[
"Spanking",
"S",
"A fairly “normal” kink that many people have tried in the bedroom. A firm hand is used as both a punishment and an enticement in many power exchange relationships, including domestic discipline relationships and schoolgirl role play. You might enjoy spanking from time to time, even if you don’t consider yourself all that kinky, but spanking can also be quite extreme."
],
[
"Spectrophilia",
"S",
"Sexual attraction to ghosts, spirits, or other similar figures might be a surprising entry on this list of fetishes."
],
[
"Stigmatophilia",
"S",
"The fetish for piercings and sometimes tattoos. See body modification fetish."
],
[
"Stockings",
"S",
"Items that are often fetishized. Some people like all of them. Others prefer lace-topped, hooked to a garter belt, or with a visible seam down the back."
],
[
"Strap-on",
"S",
"Fetish specifically for using strap-ons. Anal, oral, or vaginal penetration can be achieved. Anally penetrating a male with a strap-on is known as pegging. Here are 17 wild pegging positions you can use when you peg your partner."
],
[
"Stygiophilia",
"S",
"Arousal by thoughts of hell and eternal damnation."
],
[
"Stuffing",
"S",
"Eating until the point of physical pain."
],
[
"Suspension",
"S",
"The practice of suspending someone from the ground or being suspended yourself. Suspension can be achieved with ropes, harnesses, and other devices."
],
[
"Symphorphilia",
"S",
"Fetish for watching car accidents or other traumatic incidents."
],
[
"Taphephilia",
"T",
"Fetish for being buried alive. This may be connected to an imprisonment kink."
],
[
"Teasing (Tantalolagnia)",
"T",
"To enjoy teasing as sexual gratification. This may be prolonged sexual teasing or teasing in the form of insults and ribbing."
],
[
"Teleiophilia",
"T",
"The erotic preference for persons between the age of physical maturity and the onset of middle-age. First described in 2000 by Ray Blanchard and Howard Barbaree"
],
[
"Telephonicophilia",
"T",
"The fetish for phone sex and dirty talking over the phone."
],
[
"Tentacle fetish",
"T",
"Fetish for tentacles. Many people enjoy animated erotica/pornography with tentacles, and tentacle dildos also lend to this fantasy."
],
[
"Teratophilia",
"T",
"Attraction to people with bodily deformities. This umbrella term includes several others from our fetish list, including stigmatophilia, morphophilia, and acrotomophilia. However, it may also refer to a sexual attraction to “actual” monsters."
],
[
"Thesauromania",
"T",
"Kink for collecting women’s clothing. The collector may focus on specific items/categories such as underwear."
],
[
"Tickling (Knismolagnia, Knismo, Titillagnia)",
"T",
"While tickling can be a form of teasing, it’s a kink in its own right for some people. Those who enjoy tickling may enjoy surrendering control or struggling to retain it. Tickling to the point of urinating is also one flavor of this fetish. Tickle torture is a kink for tickling or being tickled while bound."
],
[
"Trampling fetish",
"T",
"A fetish for stepping on or being stepped on by others"
],
[
"Transformation fetish",
"T",
"A niche kink for transforming into other people or even non-human creatures. TF is common in hentai and some written erotica."
],
[
"Trichophilia",
"T",
"Hair fetish. Tips and techniques for pulling your partner’s hair."
],
[
"Troilism",
"T",
"A fetish for threesomes. This may include a kink for watching your partner have sex with someone else."
],
[
"Tripsolagnophilia",
"T",
"Massage fetish. Even if you don’t have a fetish, a sensual massage can be relaxing, and it’s good foreplay!"
],
[
"Underwear fetish",
"U",
"The fascination with underwear, usually women’s underwear. Men with this fetish will collect, wear, or smell underwear."
],
[
"Uniforms",
"U",
"Many women love a man in uniform, but not every couple incorporates this into their sex lives. Those who do just might have a uniform fetish. Uniforms, of course, can make someone seem like a powerful person (military, police, and firefighter uniforms are some of the most popular) or help you get into the role of a naif (student, waitress, Playboy bunny), and a well-fitted uniform shows off a person’s body in just the right way. If your job requires a uniform, you’re in luck. Otherwise, you can hit up a costume shop or even buy uniform-inspired lingerie."
],
[
"Ursusagalmatophilia",
"U",
"Kink for teddy bears or dressing up as a teddy bear/animal."
],
[
"Urtication",
"U",
"Using the nettle plant to sting a partner’s skin."
],
[
"Vaccinophilia",
"V",
"Vaccination fetish. See also medical play and belonephilia."
],
[
"Vicarphilia",
"V",
"Being sexually vicarious, specifically related to enjoying others’ stories of sexual activity."
],
[
"Vincilagnia",
"V",
"Kink for being tied up and at the mercy of another person. This is a type of bondage fetish."
],
[
"Vomit Fetish (Emetophilia)",
"V",
"A sexual obsession with the act or substance of vomit."
],
[
"Vore/Vorarephilia",
"V",
"Sexual desire to be eaten alive or to eat someone while they are still alive. Vore would be incredibly dangerous and illegal if attempted in reality, but it remains a fantasy for most people with it. You’ll find plenty of art and stories dedicated to vore in online communities."
],
[
"Voyeurism",
"V",
"A kink for watching someone else while naked or engaged in sexual activity. Voyeurs and exhibitionists make excellent pairings. Non-consensual voyeurism may be against the law. Ecouteurism is a related kink for listening to someone have sex without permission. The fetish is also known as scopophilia."
],
[
"Watersports (urophilia)",
"W",
"A relatively popular kink, watersports are also known as golden showers. This kink involves playing with urine, being peed on, or urinating on another person. Want to know more about golden showers? A particular form of this is wetting: urinating in one’s underwear and clothing."
],
[
"Wax play",
"W",
"Using wax during sex. Wax comes in the form of massage candles, which are relatively safe. But other types of wax may have a higher melting point and be more dangerous. Flames used to melt wax also pose a risk."
],
[
"Weapon fetish",
"W",
"Sexual arousal due to weapons. This appears in some erotic media."
],
[
"Wet and messy (WAM) fetish",
"W",
"Being turned on by being soiled by things other than bodily fluids. Also known as sploshing. This can include food."
],
[
"Xenophilia",
"X",
"Sexual attraction to exotic people or objects."
],
[
"Xylophilia",
"X",
"Fetish for wood. It may also be described as an attraction to nature, sexual or in general."
],
[
"Yogic Sexuality",
"Y",
"A type of sexuality recognizing sexual energy and its connection to the spiritual or divine"
],
[
"Yeastiality",
"Y",
"Sexual activity involving bread, especially warm dough. This may be an alleged kink. Introducing yeast to the genitals can lead to an infection."
],
[
"Yiffing",
"Y",
"Sex with stuffed animals or a furry."
],
[
"Zelophilia",
"Z",
"Arousal due to jealousy, either your own or someone’s jealousy over you. Cuckhold fantasies are an example of a kink like this, where men know – and sometimes watch – their wives engaging in affairs. Tips for exploring the cuckold kink."
],
[
"Zentai",
"Z",
"Wearing skintight suits while grinding against others in similar suits."
],
[
"Zoophilia",
"Z",
"Dressing like an animal for sex or feeling romantic attraction to animals."
],
[
"Zoosexual",
"Z",
"Sexual attraction to animals. See bestiality."
],
[
"Zwischenstufe",
"Z",
"Intense attachment to people, places, things, or other situations in transition, often or especially if those things feel fluid or ambiguous."
]
];
