// hand written from the 3Fun "list of taboo kinks" article, NOT generated, extract.py doesn't touch this
// same append only rule as data.js, taboo answers are their own link segment so this can grow on its own
// [name, summary, safety note]
const TABOO = [
  ["Power exchange (D/s)",
    "A consensual handover of control, one partner leads and the other gives it up inside limits you both agreed on. Can be a one night scene or shape the whole relationship.",
    "Set a safeword before anything starts. Using it is information, not failure."],
  ["Cuckolding / hotwifing",
    "One partner sleeps with someone else while the other watches, hears about it after, or just gives their blessing. For a lot of people the jealousy mixed with arousal is the actual kink.",
    "Keep it as fantasy and dirty talk first, and agree on the exact flavor before anything real happens."],
  ["Bondage and rope play",
    "Giving up physical freedom on purpose, anywhere from silk ties and cuffs to shibari rope work. The feeling people chase is being held, not trapped.",
    "Safety shears within reach, never leave a tied partner alone, check hands and feet for circulation, have a non verbal signal if speech is restricted."],
  ["Impact play",
    "Spanking, paddling, flogging, anything that lands as a hit. The endorphin and adrenaline spike can feel like a runner's high.",
    "Warm up light, stay off the spine, tailbone and joints, and skip it if either of you is on blood thinners. Expect a crash after, plan aftercare."],
  ["Threesomes, group play, swinging",
    "Sex with more than two people, whether that's inviting a third, a group, or swapping with another couple. Often more about watching and being watched together than the headcount.",
    "Treat a third as an equal guest, set boundaries before the night, and don't use it to patch up a shaky relationship."],
  ["Exhibitionism and voyeurism",
    "The thrill of being watched, or of watching someone else, from leaving a door open to a club full of people.",
    "Only with people who are all in on it. Watching someone who didn't agree isn't play."],
  ["Roleplay and taboo scenarios",
    "Acting out a scene you're not supposed to want, boss and employee, professor and student, strangers who shouldn't, with names and setting agreed first.",
    "Give the scene a clear start, a way out of character and a safeword so it doesn't leak into real life."],
  ["Praise kink",
    "Getting turned on by being told you're good, you're doing well, that's it. The words are the whole thing, no gear needed.",
    "About as low risk as it gets, keep the praise specific and actually meant."],
  ["Femdom and forced feminization",
    "Female led dynamics, sometimes with scripted gender roleplay where the sub gets assigned a feminine role. The force is theater, not coercion.",
    "Everything the sub is made to do still comes off a list they approved. Aftercare should reset their name, pronouns and clothes."],
  ["Chastity and orgasm control",
    "Edging, denial windows and keyholding, where one partner decides when or if the other gets to finish. The buildup is the point.",
    "Agree on a time window and a safeword up front, and plan aftercare because the release can hit hard."],
  ["Pet play",
    "One partner takes on a puppy, kitten or pony persona and the other becomes owner or handler. For plenty of people it's more about being cared for than sex.",
    "Very low risk. The persona switches off when the collar comes off."],
  ["Food, sensation and temperature play",
    "Whipped cream, ice cubes, warm oil, feathers, silk, playing with how things feel on skin.",
    "Keep food and oils away from sensitive areas and check for allergies first."],
  ["Foot fetish",
    "Attraction to feet, from massage and worship to washing them as service or being commanded by them. The most common body part fetish there is.",
    "Low risk. Asking for a foot massage with no expectations is an easy way to bring it up."],
  ["Wax and edge play",
    "Play that pushes toward a limit on purpose, hot wax, knife edges that don't cut, electro, fire.",
    "Low melt candles only, never decorative ones. Talk through the worst case and have an emergency plan before you start."],
  ["Breath play and choking",
    "Restricting breathing or putting pressure on the throat during sex. The highest risk kink on any list.",
    "Can never be made fully safe, even brief oxygen loss can cause brain damage or death. Never alone, never drunk or high. A grip that doesn't restrict breathing gets most of the same feeling."],
  ["Watersports and body fluid play",
    "Play involving urine, from shower play to golden showers. Usually more about total acceptance than the act itself.",
    "Needs explicit negotiation, waterproof covers, plenty of water to drink and agreed hygiene rules."],

  // second batch, from the "10 taboo kinks" article plus a few asked for by name. dupes skipped
  ["DDlg / MDlb and ageplay",
    "Daddy Dom / little girl, Mommy Dom / little boy and other caregiver dynamics, one partner nurtures and sets rules while the other plays a younger headspace. Everyone involved is an adult, for a lot of littles it's comforting more than anything.",
    "The little should be able to switch back to adult mode when needed. If that gets hard, take a step back and look at why."],
  ["Breeding and pregnancy kink",
    "Arousal around getting someone pregnant, being bred, or pregnant bodies themselves. Can be pure fantasy and dirty talk or tied to actually trying.",
    "Be honest about whether it's fantasy only, and sort out contraception so the fantasy stays a fantasy unless you both want otherwise. During a real pregnancy check in more, bodies change fast."],
  ["Incest roleplay",
    "Roleplay between consenting adults pretending to be related, step family scenarios being the most common. Roleplay only, the whole appeal is how forbidden it is.",
    "Strictly fantasy between unrelated adults. Agree on the roles first and keep a safeword, it can stir up real family stuff."],
  ["Forced orgasms",
    "The opposite of denial, being made to come again and again, usually while restrained, past the point where it stops feeling good and gets overwhelming.",
    "Agree on a safeword or signal you can use when overstimulated, and stop when it's used. Hydrate and go easy on sensitive skin."],
  ["CNC (consensual non consent)",
    "Scenes negotiated ahead of time where no doesn't mean stop, rape fantasy and struggle play live here. The ultimate head trip, and one of the riskiest.",
    "Needs serious negotiation, a safeword that isn't no, solid aftercare and a plan for if it brings up trauma even when everything goes right. Start small."],
  ["Race play",
    "Using racial power dynamics inside a consensual scene. For some it's reclaiming power, for others even watching it is deeply hurtful, and a lot of dungeons ban it.",
    "If you can't do a completely honest debrief afterward you're not ready. Learn from people in the communities involved before you try anything."],
  ["Cannibalism / vore roleplay",
    "Symbolic being devoured, biting, knife play, roleplaying as food. Almost always pure fantasy, and more common as a fantasy than people think.",
    "Keep it symbolic. Biting and blades still need limits, no breaking skin unless that's explicitly agreed."],
  ["Body fluid play (spit, blood)",
    "Spitting, blood, sweat and other fluids as part of play, separate from pee. Primal and edgy, also the most biologically risky thing here.",
    "Fluids carry STIs and bacteria even between long term partners. Get tested, use gloves and sterile tools for anything involving blood."],
];
